[tool.ruff]
target-version = "py310"
line-length = 100
src = ["src", "tests"]
exclude = [
  ".git",
  "__pycache__",
  ".venv",
  "htmlcov",
  "docker/services/**/data",
]

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "W",   # pycodestyle warnings
  "I",   # isort (import sorting)
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "C90", # mccabe complexity
  "N",   # pep8-naming
  "Q",   # flake8-quotes
  "RUF"  # ruff-specific rules
]
fixable = ["ALL"]
extend-unsafe-fixes = []

[tool.ruff.lint.isort]
known-first-party = ["src"]
combine-as-imports = true
order-by-type = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
docstring-code-format = true

[tool.black]
line-length = 100
target-version = ["py310"]

