# Market Making Strategy Configuration
# This configuration file defines parameters for the market making strategy
# which provides liquidity to the market through dual-sided order placement

strategy:
  name: "market_making"
  strategy_type: "market_making"
  enabled: true
  symbols: ["ETHUSDT", "BNBUSDT"]
  timeframe: "1m"
  min_confidence: 0.8
  max_positions: 10
  position_size_pct: 0.02
  stop_loss_pct: 0.02
  take_profit_pct: 0.04
  
  # Spread configuration
  base_spread: 0.001  # 0.1%
  spread_adjustment:
    volatility_multiplier: 2.0
    inventory_skew: true
    competitive_quotes: true
  
  # Order management
  order_levels: 5
  order_size_distribution: "exponential"  # or "linear", "constant"
  base_order_size: 0.01  # BTC
  size_multiplier: 1.5  # For each level
  
  # Inventory management
  target_inventory: 0.5  # 50% of max position
  max_inventory: 1.0  # BTC
  inventory_risk_aversion: 0.1
  
  # Risk parameters
  max_position_value: 10000  # USD
  stop_loss_inventory: 2.0  # BTC
  daily_loss_limit: 100  # USD
  
  # Smart features
  order_refresh_time: 30  # seconds
  adaptive_spreads: true
  competition_monitoring: true
  min_profit_per_trade: 0.00001  # BTC

# Inventory Manager Configuration
inventory_manager:
  target_inventory: 0.5
  max_inventory: 1.0
  min_inventory: -1.0
  inventory_risk_aversion: 0.1
  rebalance_threshold: 0.2  # 20% deviation
  rebalance_frequency_hours: 4
  max_rebalance_size: 0.5
  emergency_threshold: 0.8  # 80% of max
  emergency_liquidation_enabled: true

# Spread Optimizer Configuration
spread_optimizer:
  volatility_multiplier: 2.0
  volatility_window: 20
  min_volatility: 0.001  # 0.1%
  max_volatility: 0.05   # 5%
  imbalance_threshold: 0.1  # 10%
  depth_levels: 5
  min_spread: 0.0001  # 0.01%
  max_spread: 0.01    # 1%
  competitor_monitoring: true
  competitor_weight: 0.3
  max_competitor_spread: 0.005  # 0.5%
  impact_threshold: 0.001  # 0.1%
  impact_multiplier: 1.5

# Performance Targets
performance:
  target_uptime: 0.95  # 95% uptime
  target_inventory_range: 0.90  # 90% within target range
  target_spread_response: 10  # seconds
  target_order_refresh: 0.99  # 99% reliable refresh
  target_competitive_positioning: true

# Risk Management Integration
risk_management:
  max_daily_loss: 100  # USD
  max_drawdown: 0.15   # 15%
  position_limit: 2.0   # BTC
  correlation_limit: 0.5  # 50%
  volatility_limit: 0.05  # 5%

# Exchange-Specific Settings
exchanges:
  binance:
    enabled: true
    symbols: ["ETHUSDT", "BNBUSDT"]
    rate_limit_buffer: 0.8  # 80% of rate limit
    order_refresh_interval: 30  # seconds
    
  okx:
    enabled: true
    symbols: ["ETH-USDT", "BNB-USDT"]
    rate_limit_buffer: 0.8
    order_refresh_interval: 30
    
  coinbase:
    enabled: false  # Disabled by default
    symbols: ["ETH-USD", "BNB-USD"]
    rate_limit_buffer: 0.8
    order_refresh_interval: 30

# Monitoring and Alerts
monitoring:
  enable_performance_tracking: true
  enable_inventory_monitoring: true
  enable_spread_optimization_tracking: true
  alert_on_emergency_liquidation: true
  alert_on_rebalance_frequency: true
  alert_on_spread_widening: true

# Logging Configuration
logging:
  level: "INFO"
  enable_debug_logs: false
  log_inventory_changes: true
  log_spread_adjustments: true
  log_order_placements: true
  log_rebalancing_events: true
