_metadata:
  last_updated: '2025-10-04T16:18:22.168503+00:00'
  version: 1.0.0
acceleration_factor: null
created_at: 2025-10-04 16:18:22.168387+00:00
enabled: true
entry_threshold: null
exchange_type: null
exit_threshold: null
inventory_target: null
lookback_period: null
max_position_size: null
max_positions: 5
metadata: {}
min_confidence: 0.6
momentum_threshold: null
name: test_string_type
num_std: null
parameters:
  entry_threshold: 2.0
  exit_threshold: 0.5
  lookback_period: 20
  volatility_window: 20
position_size_pct: 0.02
requires_exchange: false
requires_risk_manager: false
risk_parameters: {}
spread_pct: null
stop_loss_pct: 0.02
strategy_id: test_string_type_404
strategy_type: mean_reversion
symbol: BTCUSDT
take_profit_pct: 0.04
timeframe: 5m
updated_at: null
window_size: null
