"""
Core Framework Package

This package contains the core framework components including types, configuration,
exceptions, and logging systems.
"""

# Core framework exports
from .base import BaseComponent, BaseService, HealthStatus, TransactionalService
from .base.health import HealthCheckResult
from .base.interfaces import ServiceComponent
from .caching import CacheKeys, CacheManager, cache_invalidate, cached, get_cache_manager
from .config import Config, DatabaseConfig
from .config.service import ConfigService
from .dependency_injection import get_container
from .exceptions import (
    AuthenticationError,
    ComponentError,
    ConfigurationError,
    DatabaseError,
    DataError,
    DataSourceError,
    DataValidationError,
    DependencyError,
    EmergencyStopError,
    ErrorCategory,
    ExchangeConnectionError,
    ExchangeError,
    ExchangeErrorMapper,
    ExchangeInsufficientFundsError,
    ExchangeRateLimitError,
    ExecutionError,
    ModelError,
    MonitoringError,
    NetworkError,
    OrderRejectionError,
    PositionLimitError,
    RiskManagementError,
    SecurityError,
    ServiceError,
    SignalGenerationError,
    StateConsistencyError,
    StateError,
    TradingBotError,
    ValidationError,
)
from .logging import (
    PerformanceMonitor,
    correlation_context,
    get_logger,
    get_secure_logger,
    log_async_performance,
    log_performance,
    setup_logging,
)
from .types import (
    BotConfiguration,
    BotPriority,
    BotState,
    BotStatus,
    BotType,
    DriftType,
    ErrorPattern,
    ExchangeInfo,
    ExchangeStatus,
    ExecutionAlgorithm,
    ExecutionInstruction,
    ExecutionResult,
    IngestionMode,
    MarketData,
    NewsSentiment,
    OrderBook,
    OrderRequest,
    OrderResponse,
    OrderSide,
    OrderStatus,
    OrderType,
    PipelineStatus,
    Position,
    ProcessingStep,
    QualityLevel,
    Signal,
    SignalDirection,
    SocialSentiment,
    StorageMode,
    Ticker,
    Trade,
    TradingMode,
    ValidationLevel,
    ValidationResult,
)

__all__ = [
    "AuthenticationError",
    "BaseComponent",
    "BaseService",
    "BotConfiguration",
    "BotPriority",
    "BotState",
    "BotStatus",
    "BotType",
    "CacheKeys",
    "CacheManager",
    "ComponentError",
    "Config",
    "ConfigService",
    "ConfigurationError",
    "DataError",
    "DataSourceError",
    "DataValidationError",
    "DatabaseConfig",
    "DatabaseError",
    "DependencyError",
    "DriftType",
    "EmergencyStopError",
    "ErrorCategory",
    "ErrorPattern",
    "ExchangeConnectionError",
    "ExchangeError",
    "ExchangeErrorMapper",
    "ExchangeInfo",
    "ExchangeInsufficientFundsError",
    "ExchangeRateLimitError",
    "ExchangeStatus",
    "ExecutionAlgorithm",
    "ExecutionError",
    "ExecutionInstruction",
    "ExecutionResult",
    "HealthCheckResult",
    "HealthStatus",
    "IngestionMode",
    "MarketData",
    "ModelError",
    "MonitoringError",
    "NetworkError",
    "NewsSentiment",
    "OrderBook",
    "OrderRejectionError",
    "OrderRequest",
    "OrderResponse",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PerformanceMonitor",
    "PipelineStatus",
    "Position",
    "PositionLimitError",
    "ProcessingStep",
    "QualityLevel",
    "RiskManagementError",
    "SecurityError",
    "ServiceComponent",
    "ServiceError",
    "Signal",
    "SignalDirection",
    "SignalGenerationError",
    "SocialSentiment",
    "StateConsistencyError",
    "StateError",
    "StorageMode",
    "Ticker",
    "Trade",
    "TradingBotError",
    "TradingMode",
    "TransactionalService",
    "ValidationError",
    "ValidationLevel",
    "ValidationResult",
    "cache_invalidate",
    "cached",
    "correlation_context",
    "get_cache_manager",
    "get_container",
    "get_logger",
    "get_secure_logger",
    "log_async_performance",
    "log_performance",
    "setup_logging",
]
