"""
Core Framework Package

This package contains the core framework components including types, configuration,
exceptions, and logging systems.
"""

# Core framework exports
from .base import HealthStatus, TransactionalService
from .caching import CacheKeys, cached, get_cache_manager
from .config import Config, DatabaseConfig
from .exceptions import (
    AuthenticationError,
    ConfigurationError,
    DataError,
    ErrorCategory,
    ExchangeConnectionError,
    ExchangeError,
    ExchangeErrorMapper,
    ExchangeRateLimitError,
    ExecutionError,
    ModelError,
    NetworkError,
    OrderRejectionError,
    RiskManagementError,
    SecurityError,
    ServiceError,
    StateConsistencyError,
    StateError,
    TradingBotError,
    ValidationError,
)
from .logging import (
    PerformanceMonitor,
    correlation_context,
    get_logger,
    get_secure_logger,
    log_async_performance,
    log_performance,
    setup_logging,
)
from .types import (
    BotConfiguration,
    BotPriority,
    BotState,
    BotStatus,
    BotType,
    DriftType,
    ErrorPattern,
    ExecutionAlgorithm,
    ExecutionInstruction,
    ExecutionResult,
    IngestionMode,
    MarketData,
    NewsSentiment,
    OrderRequest,
    OrderResponse,
    OrderSide,
    OrderType,
    PipelineStatus,
    Position,
    ProcessingStep,
    QualityLevel,
    Signal,
    SignalDirection,
    SocialSentiment,
    StorageMode,
    TradingMode,
    ValidationLevel,
    ValidationResult,
)

__all__ = [
    "AuthenticationError",
    "BotConfiguration",
    "BotPriority",
    "BotState",
    "BotStatus",
    "BotType",
    "CacheKeys",
    "Config",
    "ConfigurationError",
    "DataError",
    "DatabaseConfig",
    "DriftType",
    "ErrorCategory",
    "ErrorPattern",
    "ExchangeConnectionError",
    "ExchangeError",
    "ExchangeErrorMapper",
    "ExchangeRateLimitError",
    "ExecutionAlgorithm",
    "ExecutionError",
    "ExecutionInstruction",
    "ExecutionResult",
    "HealthStatus",
    "IngestionMode",
    "MarketData",
    "ModelError",
    "NetworkError",
    "NewsSentiment",
    "OrderRejectionError",
    "OrderRequest",
    "OrderResponse",
    "OrderSide",
    "OrderType",
    "PerformanceMonitor",
    "PipelineStatus",
    "Position",
    "ProcessingStep",
    "QualityLevel",
    "RiskManagementError",
    "SecurityError",
    "ServiceError",
    "Signal",
    "SignalDirection",
    "SocialSentiment",
    "StateConsistencyError",
    "StateError",
    "StorageMode",
    "TradingBotError",
    "TradingMode",
    "TransactionalService",
    "ValidationError",
    "ValidationLevel",
    "ValidationResult",
    "cached",
    "correlation_context",
    "get_cache_manager",
    "get_logger",
    "get_secure_logger",
    "log_async_performance",
    "log_performance",
    "setup_logging",
]
